version: 2

sources:
  - name: library
    schema: main
    tables:
      - name: books_factual
      - name: books_fictional
      - name: loans
      - name: members

models:
  - name: stg_books
    columns:
      - name: book_id
        data_tests:
          - unique
          - not_null

  - name: stg_members
    columns:
      - name: membership_tier
        tests:
          - accepted_values:
              values: ['Bronze','Silver', 'Gold']
      - name: member_id
        data_tests:
          - not_null
      - name: member_name
        tests:
          - contains_digits:
              severity: warn

  - name: stg_loans
    columns:
      - name: loan_id
        data_tests:
          - not_null
      - name: book_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_books')
              field: book_id
      - name: member_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_members')
              field: member_id

  - name: customers_with_late_fees
    columns:
      - name: fee_to_pay
        tests:
          - non_negative
      - name: member_name
        tests:
          - one_row_per_customer
      - name: member_name
        tests:
          - contains_digits:
              severity: warn
    tests:
      - dbt_utils.equal_rowcount:
          compare_model: ref('solution')


  - name: customer_withdrawals
    columns:
      - name: member_name
        tests:
          - contains_digits:
              severity: warn

seeds:
  - name: solution
  